"""PostgreSQL query contract tests; no external database is needed."""

import os
import sys
import unittest
from types import ModuleType
from unittest.mock import Mock, patch

from src.controller import create_server
from src.main import main
from src.model import PostgresHistoryRepository


DATABASE_URL = "postgresql://example:secret@localhost:5432/calculator"


class FakePostgresError(Exception):
    pass


class FakeCursor:
    def __init__(self, statements):
        self.statements = statements
        self.rowcount = 0

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        return False

    def execute(self, sql, params=None):
        self.statements.append((sql, params))
        if sql.startswith("DELETE"):
            self.rowcount = 1 if params == (1,) else 0
        return self

    def fetchone(self):
        return (1,)

    def fetchall(self):
        return [(1, "0.1+0.2", "0.3", "2026-09-26T00:00:00+00:00")]


class FakeConnection:
    def __init__(self):
        self.statements = []
        self.rollbacks = 0
        self.closed = False

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        self.closed = True
        return False

    def cursor(self):
        return FakeCursor(self.statements)

    def rollback(self):
        self.rollbacks += 1


def fake_psycopg(connections):
    driver = ModuleType("psycopg")
    driver.Error = FakePostgresError
    driver.connect = Mock(side_effect=lambda *_args, **_kwargs: connections.pop(0))
    return driver


class PostgresHistoryRepositoryTests(unittest.TestCase):
    def test_crud_uses_parameterized_queries_and_closes_connections(self):
        connections = [FakeConnection() for _ in range(6)]
        driver = fake_psycopg(connections.copy())
        with patch.dict(sys.modules, {"psycopg": driver}):
            repository = PostgresHistoryRepository(DATABASE_URL)
            record = repository.add("0.1+0.2", "0.3")
            history = repository.list()
            deleted = repository.delete(1)
            missing = repository.delete(99)

        self.assertEqual(driver.connect.call_count, 6)
        driver.connect.assert_called_with(DATABASE_URL, connect_timeout=10)
        self.assertTrue(all(connection.closed for connection in connections))
        self.assertIn("CREATE TABLE IF NOT EXISTS calculation_history", connections[0].statements[0][0])
        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY", connections[0].statements[0][0])
        self.assertEqual(connections[1].statements[0][1], ("startup-probe", "0", "startup-probe"))
        self.assertEqual(connections[1].rollbacks, 1)
        self.assertIn("RETURNING id", connections[2].statements[0][0])
        self.assertEqual(connections[2].statements[0][1][0:2], ("0.1+0.2", "0.3"))
        self.assertEqual(record.id, 1)
        self.assertEqual(record.result_text, "0.3")
        self.assertEqual(record.result, 0.3)
        self.assertIn("ORDER BY id DESC", connections[3].statements[0][0])
        self.assertEqual(history[0].to_dict()["result_text"], "0.3")
        self.assertEqual(connections[4].statements[0][1], (1,))
        self.assertEqual(connections[5].statements[0][1], (99,))
        self.assertTrue(deleted)
        self.assertFalse(missing)

    def test_unreachable_database_fails_at_startup_without_leaking_url(self):
        driver = ModuleType("psycopg")
        driver.Error = FakePostgresError
        driver.connect = Mock(side_effect=FakePostgresError("secret"))
        with patch.dict(sys.modules, {"psycopg": driver}):
            with self.assertRaisesRegex(RuntimeError, "not reachable or writable") as caught:
                PostgresHistoryRepository(DATABASE_URL)
        self.assertNotIn("secret", str(caught.exception))

    def test_invalid_database_url_fails_before_connecting(self):
        with self.assertRaisesRegex(RuntimeError, "PostgreSQL connection URL"):
            PostgresHistoryRepository("sqlite:///history.db")

    def test_server_selects_postgres_when_database_url_is_provided(self):
        with patch("src.controller.PostgresHistoryRepository") as postgres_repository:
            with patch("src.controller.HistoryRepository") as sqlite_repository:
                server = create_server("127.0.0.1", 0, "unused.db", database_url=DATABASE_URL)
                try:
                    postgres_repository.assert_called_once_with(DATABASE_URL)
                    sqlite_repository.assert_not_called()
                finally:
                    server.server_close()

    def test_render_requires_database_url_instead_of_temporary_sqlite(self):
        with patch.dict(os.environ, {"RENDER": "true", "DATABASE_URL": ""}):
            with self.assertRaisesRegex(SystemExit, "DATABASE_URL is required on Render"):
                main()


if __name__ == "__main__":
    unittest.main()
